### ISSUE TITLE
你好 能问个问题吗 

### ISSUE THREAD

**Issue by hipi** [l-Lemon/react-architecture#1]
你第一篇这样安装```npm install -D babel-core babel-loader babel-preset-env babel-preset-react babel-preset-stage-2 babel-polyfill```
可我看你的```package.json``` 只有```babel-polyfill``` 在 ```dependencies```里·

**Comment by william-xue** [comment]
报错 跑不通

**Comment by ZeroCodeLin** [comment]
@chenyeah  你看 `devDependencies`里面

**Comment by ZeroCodeLin** [comment]
@william-xue  报什么错？

**Comment by hipi** [comment]
@l-Lemon ```npm install -D babel-core babel-loader babel-preset-env babel-preset-react babel-preset-stage-2 babel-polyfill```这样安装,```babel-polyfill```会在```devDependencies```,实际生产环境```babel-polyfill```也要用到 ，所以你这步安装错了！

**Comment by hipi** [comment]
@l-Lemon  建议，升级为 webpack@4 :smiley:

**Comment by ZeroCodeLin** [comment]
@chenyeah  是的，应该`npm install -S babel-polyfill`， 请原谅我偷懒复制粘贴了。 后面会升级到webpack@4的。

**Comment by hipi** [comment]
@l-Lemon 你文章写得真的不错

**Comment by ZeroCodeLin** [comment]
@chenyeah 谢谢夸奖， 还差很多， 文章已更正， 发现问题欢迎随时指正。
